name: CICD - AUTH - DEV

on:
    push:
        branches:
            - dev
        paths:
            - 'auth/**'
            - 'common/**'

env:
    ECR_REPOSITORY: torder-authorization-v2

permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  role-to-assume : ${{ secrets.AWS_ASSUME_BACKEND }}
                  aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

            - name : Login to Amazon ECR
              id : login-ecr
              uses : aws-actions/amazon-ecr-login@v1

            - name: Auth Module Build and push image to Amazon ECR
              id: auth-build-image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
              run: |
                  cd auth
                  ../gradlew bootBuildImage --imageName=$ECR_REGISTRY/$ECR_REPOSITORY:dev
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev

            - name: Update ECS service
              run: |
                  aws ecs update-service --cluster torder-dev --service ${{ env.ECR_REPOSITORY }} --force-new-deployment